<a href="https://colab.research.google.com/github/Shrinivas18/Python_Numpy/blob/main/Concatenate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
# Concatenate

# Concatenate
# Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:

# import numpy

# array_1 = numpy.array([1,2,3])
# array_2 = numpy.array([4,5,6])
# array_3 = numpy.array([7,8,9])

# print numpy.concatenate((array_1, array_2, array_3))    

#Output
# [1 2 3 4 5 6 7 8 9]

# If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default, it
# is along the first dimension.

# import numpy

# array_1 = numpy.array([[1,2,3],[0,0,0]])
# array_2 = numpy.array([[0,0,0],[7,8,9]])

# print numpy.concatenate((array_1, array_2), axis = 1)   

#Output
# [[1 2 3 0 0 0]
#  [0 0 0 7 8 9]]

# Task
# You are given two integer arrays of size NxP and MxP (N & M are rows, and P is the column). Your task is to concatenate the arrays
# along axis 0.

# Input Format
# The first line contains space separated integers N, M and P. 
# The next N lines contains the space separated elements of the P columns. 
# After that, the next M lines contains the space separated elements of the P columns.

# Output Format
# Print the concatenated array of size (N+M)xP.


import numpy

N = numpy.array([input().split() for i in range(1)], int)
M = numpy.array([input().split() for i in range(1)], int)

print(numpy.concatenate((N, M), axis = 0))


1 2 3 4 45
2 1 43 12 31
[[ 1  2  3  4 45]
 [ 2  1 43 12 31]]
