<a href="https://colab.research.google.com/github/Shrinivas18/Python_Numpy/blob/main/Transpose_and_Flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Transpose

# We can generate the transposition of an array using the tool numpy.transpose. 
# It will not affect the original array, but it will create a new array.

# Flatten

# The tool flatten creates a copy of the input array flattened to one dimension.

# Task
# You are given a N X M integer array matrix with space separated elements (N = rows and M = columns). 
# Your task is to print the transpose and flatten results.

# Input Format
# The first line contains the space separated values of N and M. 
# The next N lines contains the space separated elements of M columns.

# Output Format
# First, print the transpose array and then print the flatten.

import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

3 3
1 2 3
4 5 6
7 8 9
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
